# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "iostreamer"
description: > # this means to ignore newlines until "email:"
   ideas are bulletproof

email: iostreamer@amethystlabs.org
#blog logo
logo: "/assets/images/io.jpg"
# blog cover
cover: "/assets/images/witcher.jpg"

name: 'iostreamer'
author: 'iostreamer'
author_image: "/assets/images/io.jpg"

paginate:	5

url: "http://iostreamer.me" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@_iostreamer_'

#fill in disqus shortname to use disqus
disqus: io-streamer

# social icons and sharing options
social:
