# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "iostreamer"
description: > # this means to ignore newlines until "email:"
   ideas are bulletproof

email: iostreamer@amethystlabs.org
#blog logo
logo: "/assets/images/io.jpg"
# blog cover
cover: "/assets/images/L.jpg"

name: 'iostreamer'
author: 'iostreamer'
author_image: "/assets/images/io.jpg"

paginate:	5

url: "http://blog.iostreamer.me" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@_iostreamer_'

#fill in disqus shortname to use disqus
disqus: io-streamer

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/_iostreamer_
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/rahul.iostreamer
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/iostreamer-X
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/100193742345396424276
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:
